### ISSUE TITLE
Basic logic tracking of nested game functionality

### ISSUE THREAD

**Issue by KassAdams** [KassAdams/SeniorDesign#17]
### Includes:

- [x] extending tracking/checking of inner games won beyond just top left
- [x] structuring data objects to facilitate better tracking of innerGames, winners, win count
- [x] documenting functionality and refactoring
- [ ] adding draw option

**Comment by KassAdams** [comment]
@paytonelsey If you git checkout my branch and run it you can see some of the changes I've made. None of it affected the basic css or html you had implemented when I pull so it should be good okay to merge later. I'm just gonna add a "tie/draw" option and refactor/document a little better then I can setup a PR and work on some testing or something
